version: '3.9'

services:
  api:
    build:
      context: ./src/api
      dockerfile: ./docker/Dockerfile
    container_name: api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - messeger
  taker:
    build:
      context: ./src/taker
      dockerfile: ./docker/Dockerfile
    container_name: taker
    restart: always
    depends_on:
      - messeger
  messeger:
    image: redis:7-alpine
    container_name: messeger
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/messeger:/var/lib/redis/data
